apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "creds-capability-checks"
    #annotations:
  #author: "Djalal Harouni"
spec:
  kprobes:
    - call: "cap_capable"
      syscall: false
      return: true
      args:
        - index: 1
          type: "user_namespace"
        - index: 2
          type: "capability"
      returnArg:
        index: 0
        type: "int"
      selectors:
        - matchNamespaces:
            - namespace: Pid
              operator: NotIn
              values:
                - "host_ns"
          matchActions:
            - action: Post