apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "tcp-send-monitoring"
spec:
  kprobes:
    - call: "tcp_sendmsg"
      syscall: false
      args:
        - index: 0
          type: "sock"
        - index: 1
          type: "size_t"
      selectors:
        - matchArgs:
            - index: 0
              operator: "NotDAddr"
              values:
                - "127.0.0.1"
      tags: [ "observability.network"]
    - call: "tcp_recvmsg"
      syscall: false
      args:
        - index: 0
          type: "sock"
        - index: 1
          type: "size_t"
      selectors:
        - matchArgs:
            - index: 0
              operator: "NotDAddr"
              values:
                - "127.0.0.1"
      tags: [ "observability.network" ]

